apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: REPLACE_WITH_CLUSTER_CA_DATA
    server: https://REPLACE_WITH_CLUSTER_ENDPOINT
  name: gke_chas-devsecops-2026_europe-north1_chas-devsecops-cluster
contexts:
- context:
    cluster: gke_chas-devsecops-2026_europe-north1_chas-devsecops-cluster
    namespace: m4k-gang
    user: M4K Gang
  name: M4K Gang
current-context: M4K Gang
users:
- name: M4K Gang
  user:
    token: REPLACE_WITH_VALID_TOKEN
