# Monitor API Key Secret
# Contains the API key for authenticating with Team Flags

apiVersion: v1
kind: Secret
metadata:
  name: monitor-secret
  # TODO: Change namespace to your team name
  namespace: m4k-gang
  labels:
    app: team-monitor
type: Opaque
stringData:
  # API key will be pre-filled when you download from Mission Control
  API_KEY: "tfk_kHurD4vB2Eww0R7no6gB2B4puX9gStv5WnGeEpi0kMM"

